language: ruby
rvm:
  - 2.2.1

services:
  - postgresql

# Setup Test Database
before_script:
  - psql -c 'create database helpy_test;' -U postgres

script:
  # Migrate database
  - bin/rake db:migrate RAILS_ENV=test
  # Test suite
  - bundle exec rake
  # Brakeman security scanner
  - bundle exec brakeman -z
  # Check vulnerable gems
  - bundle exec bundle-audit check --update
  # Rubocop static code analyzer
  - bundle exec rubocop
  # SCSS analyzer
  - bundle exec scss-lint

cache: bundler

addons:
    code_climate:
        repo_token: 8aed69acf532241f5281042dc5b1a5d89ea9206773d079ce2de838a28f0f5041
