---
- name: add keyscan to allow basic access to github
  shell: ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts

- name: add keyscan to allow basic access to Bitbucket
  shell: ssh-keyscan bitbucket.org >> /etc/ssh/ssh_known_hosts

- name: install basic packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - build-essential
    - git-core
    - curl
    - wget
    - cmake
    - python-dev

- name: add apt-get repository for latest vim
  action: apt_repository repo=ppa:fcwu-tw/ppa

- name: install vim
  apt: name=vim state=latest update_cache=yes

- name: copy .vimrc
  template: src=vimrc dest=/home/{{server_user}}/.vimrc owner={{server_user}} group={{server_user}}

- name: change .vim permissions
  file: path=/home/{{server_user}}/.vim owner={{server_user}} group={{server_user}} recurse=yes state=directory

- name: set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
